training:
  model_name: "hf-hub:imageomics/bioclip"
  pretrained_path: "/Users/daoud/PycharmAssets/xprize/open_clip_pytorch_model.bin" # "default/path/to/pretrained/model"
  test_size: 0.2
  random_state: 42
  batch_size: 12
  hidden_dim: 1024
  num_epochs: 400
  learning_rate: 0.001
  loss: cross_entropy
  n_neighbors: 10
  kernel: linear
  num_workers: 4

data:
  dir_path: '/Users/daoud/PycharmAssets/xprize/'
  taxonomy_file: 'photos_exif_taxo.csv'
  # 10597
  folder_pattern: 'competition_data/preprocessed/set_7/300/*zoom_cropped'
  num_folders: 500  # Set to a number to limit the number of folders
  shuffle: False

active_learner:
  sample_dbscan_points_per_cluster: 10
  sample_size: 20
  max_iterations: 20
  visualize_clusters: True
  visualize_dbscan: True
