model_name: "hf-hub:imageomics/bioclip"
pretrained_path: "/Users/daoud/PycharmAssets/xprize/open_clip_pytorch_model.bin" # "default/path/to/pretrained/model"
test_size: 0.3
random_state: 42
batch_size: 12
hidden_dim: 1024
num_epochs: 400
learning_rate: 0.001
loss: cross_entropy
n_neighbors: 10
kernel: linear
