source_data_root: /home/hugo/Documents/xprize/data/FINAL_polygon_dataset_1536px_gr0p03
use_datasets: ['panama', 'quebec', 'equator'] #'quebec', 'equator', 'brazil']  #['quebec', 'panama', 'equator', 'brazil']
freeze_resnet_backbone: true
max_resampling_times_train: 50
max_resampling_times_valid_train: 0
valid_knn_k: 5
min_level: 'genus'
distance: 'euclidean'  # cosine
resnet_model: resnet50
use_multi_gpu: true
start_from_checkpoint: "/home/hugo/Documents/xprize/trainings_resnet/contrastive_resnet50_224_768_64_genus_1720390152/checkpoint_15_63728.pth"
learning_rate: 0.0001  # 0.0001
train_batch_size: 64
triplet_sampler_m: 8
n_grad_accumulation_steps: 1
valid_batch_size_multiplier: 8
validate_every_n_epochs: 5
image_size: 224
random_crop: true
loss_weight_triplet: 1.0
loss_weight_classification: 0
triplet_margin: 0.5
triplet_type: 'all'
dropout: 0.3
final_embedding_size: 768
scheduler_name: 'cosine'
scheduler_gamma: 0.975
scheduler_T: 30
scheduler_T_mult: 2
n_warmup_epochs: 1
num_epochs: 100
data_loader_num_workers: 4
phylogenetic_tree_distances_path: /home/hugo/Documents/xprize/data/pairs_with_dist.csv
output_folder_root: /home/hugo/Documents/xprize/trainings_resnet
