source_data_root: /home/hugo/Documents/xprize/data/FINAL_polygon_dataset_1536px_gr0p03
use_datasets: ['panama'], #'quebec', 'equator', 'brazil']  #['quebec', 'panama', 'equator', 'brazil']
max_resampling_times_train: 50
max_resampling_times_valid_train: 4
valid_knn_k: 5
min_level: 'genus'
distance: 'euclidean'  # cosine
resnet_model: resnet50
use_multi_gpu: true
start_from_checkpoint: null  # "/home/hugo/Documents/xprize/trainings/contrastive_resnet50_768_1024_144_mpt_1719091279/checkpoint_0.pth"
learning_rate: 0.0002  # 0.0001
train_batch_size: 32
n_grad_accumulation_steps: 2
valid_batch_size_multiplier: 1
image_size: 224
random_crop: true
loss_weight_triplet: 1.0
loss_weight_classification: 1.5
triplet_margin: 0.5
triplet_type: 'all'
dropout: 0.5
final_embedding_size: 1024
scheduler_T: 30
n_warmup_epochs: 5
num_epochs: 100
data_loader_num_workers: 4
phylogenetic_tree_distances_path: /home/hugo/Documents/xprize/data/pairs_with_dist.csv
output_folder_root: /home/hugo/Documents/xprize/trainings_2
