aggregator:
    io:
        input_tiles_root: 'Data\pre_processed\all_datasets\quebec_trees\2021_09_02_sbl_z1_rgb_cog\tiles'
        coco_path: '.\output\test\detector_infer1\2021_09_02_sbl_z1_rgb_cog_coco_sf1p0_infer.json'
        output_folder: '.\output\test\aggregator1'
        output_type:       # TODO TODO TODO           ->          'coco' or 'geojson'
    score_threshold: 0.4
    nms_threshold: 0.7
    nms_algorithm: 'iou'