output:
    output_folder: ./output
    output_name: detector_quebec
model_config:
    batch_size: 16
    learning_rate: 5e-4
    n_epochs: 50
    rcnn_backbone_model_resnet_name: resnet50
    rcnn_backbone_model_pretrained: True
    backbone_resnet_out_channels: 2048
    box_predictions_per_image: 100
tiles:
    chip_size: 1024,
    chip_stride: 512
datasets:
    train: [
            {
              name: quebec_trees_Z1,
              data_root: Data/pre_processed/quebec_trees/Z1_quebec_trees,
            },
            {
              name: quebec_trees_Z2,
              data_root: Data/pre_processed/quebec_trees/Z2_quebec_trees,
            },
    ]
    valid: [
        {
            name: quebec_trees_Z3_valid,
            data_root: Data/pre_processed/quebec_trees/Z3_quebec_trees_valid,
        },
    ]
    test: [
        {
            name: quebec_trees_Z3_test,
            data_root: Data/pre_processed/quebec_trees/Z3_quebec_trees_test,
        },
    ]