data_root_path: 'Data/pre_processed/all_datasets'
batch_size: 25
architecture:
    name: 'basic'
    rcnn_backbone_model_resnet_name: 'resnet50'
train:
    output:
        output_folder: './output'
        output_name: 'detector_1'
        train_log_interval: 50      # in step=batch
    model_config:
        rcnn_backbone_model_pretrained: true
        start_checkpoint_state_dict_path: null
        learning_rate: 5e-4
        n_epochs: 500
        save_model_every_n_epoch: 5
        backbone_resnet_out_channels: 2048
        box_predictions_per_image: 250
        scheduler_step_size: 10     # here, step=epochs
        scheduler_gamma: 0.1
score:
    checkpoint_state_dict_path: './output/detector_quebec/detector_checkpoint.pt'
    box_predictions_per_image: 250
infer:
    checkpoint_state_dict_path: './output/detector_quebec/detector_checkpoint.pt'
    box_predictions_per_image: 250