embedder:
    infer:
        io:
              input_tiles_root: 'pre_processed\final_dataset_polygons\quebec_trees\2021_09_02_sbl_z3_rgb_cog\tiles'
              coco_path: 'pre_processed\final_dataset_polygons\quebec_trees\2021_09_02_sbl_z3_rgb_cog\2021_09_02_sbl_z3_rgb_cog_coco_gr0p05_test.json'
              output_folder: 'embeddings\embeddings_siamese_2021_09_02_sbl_z3_rgb_cog_coco_gr0p05_test'
        batch_size: 16
        siamese:
            checkpoint_path: 'models\embedder_quebec\checkpoint_0_20000.pth'
            architecture:
                architecture_name: 'siamese'
                backbone_model_resnet_name: 'resnet50'
                final_embedding_size: 1024
