io:
    raster_path: ''
    aoi_geopackage_path: null
    segmentations_geopackage_path: ''
    output_folder: ''
    day_month_year: null #[1, 1, 2021]

pipeline_classifier:
    tilerizer:
        tile_type: 'polygon'
        tile_size: 2048  # this is just the max allowed when use_variable_tile_size = True
        use_variable_tile_size: true
        variable_tile_size_pixel_buffer: 10
        tile_overlap: null
        raster_resolution:
            scale_factor: null
            ground_resolution: 0.03
        ignore_black_white_alpha_tiles_threshold: null

    embedder:
        infer:  # can set either 'contrastive' or 'dinov2', or both if both embedders are needed
            batch_size: 16
            contrastive:
                backbone_name: 'resnet50'
                mean_std_descriptor: 'forest_qpeb'
                image_size: 224
                final_embedding_size: 768
                checkpoint_path: 'path/to/contrastive_resnet50_224_768_64_genus_1720407357/checkpoint_15_63728.pth'
            dinov2:
                size: 'base'
                use_cls_token: False
                image_size_center_crop_pad: 224
                instance_segmentation: False
                mean_std_descriptor: 'imagenet'