io:
    raster_path: ''
    output_folder: ''
    coco_n_workers: 5

pipeline_detector:
    save_detector_intermediate_output: false

    tilerizer:
        tile_type: 'tile'
        tile_size: 1024
        tile_overlap: 0.5
        raster_resolution:
            scale_factor: null
            ground_resolution: 0.05
        ignore_black_white_alpha_tiles_threshold: 0.8
        area_of_interest: {
            aoi_config: 'generate',
            aoi_type: 'band',
            aois: {
              'infer': {
                'percentage': 1.0,
                'position': 1
              }
            }
        }

    detector:
        infer:
            io:
                checkpoint_state_dict_path: './output/detector_quebec/detector_checkpoint.pt'
            base_params:
                batch_size: 25
                box_predictions_per_image: 250
            architecture:
                architecture_name: 'fasterrcnn'
                backbone_model_resnet_name: 'resnet50'

    aggregator:
        polygon_type: 'box'
        score_threshold: 0.4
        nms_threshold: 0.7
        nms_algorithm: 'iou'