io:
    raster_path: ''
    boxes_geopackage_path: ''
    output_folder: ''

pipeline_segmenter:
    save_segmenter_intermediate_output: false

    tilerizer:
        tile_type: 'tile'
        tile_size: 1024
        tile_overlap: 0.5
        raster_resolution:
            scale_factor: null
            ground_resolution: 0.05
        ignore_black_white_alpha_tiles_threshold: 0.8
        area_of_interest: {
            aoi_config: 'generate',
            aoi_type: 'band',
            aois: {
              'infer': {
                'percentage': 1.0,
                'position': 1
              }
            }
        }

    segmenter:
        infer:
            model_type: 'vit_l'
            checkpoint_path: 'Data/models/sam/sam_vit_l_0b3195.pth'
            simplify_tolerance: 1.0
            box_padding_percentage: 0.00
            n_postprocess_workers: 16
            box_batch_size: 500


    aggregator:
        scores_weights: {'segmenter_score': 1.0} # or {'detector_score': 3.0, 'segmenter_score': 1.0}
        polygon_type: 'segmentation'
        score_threshold: 0.05
        nms_threshold: 0.5
        nms_algorithm: 'iou'