data_path: Data/raw/quebec_trees_dataset_2021-09-02/2021-09-02/zone1/2021-09-02-sbl-z1-rgb-cog.tif
annot_path: Data/raw/quebec_trees_dataset_2021-09-02/Z1_polygons.gpkg
output_folder: Data/pre_processed/quebec_trees/Z1_quebec_trees
tile_size: 1024
tile_overlap: 0.5
area_of_interest:
  xmin: 0.0
  ymin: 0.0
  xmax: 1.0
  ymax: 1.0