raster_path: 'Data/raw/quebec_trees_dataset_2021-09-02/2021-09-02/zone1/2021-09-02-sbl-z1-rgb-cog.tif'
labels_path: 'Data/raw/quebec_trees_dataset_2021-09-02/Z1_polygons.gpkg'
output_folder: 'Data/pre_processed/quebec_trees/Z1_quebec_trees'
tile_size: 1024
tile_overlap: 0.5
scale_factor: 0.5
ignore_black_white_alpha_tiles_threshold: 0.8
ignore_tiles_without_labels: True
main_label_category_column_name: 'Label'
area_of_interest: {
    aoi_config: 'generate',
    aoi_type: 'band',
    aois: {
      'train': {
        'percentage': 0.7,
        'position': 2
      },
       'valid': {
         'percentage': 0.15,
         'position': 1
      },
       'test': {
         'percentage': 0.15,
         'position': 3
      }
    }
}
