segmenter:
    io:
      input_tiles_root: 'Data\pre_processed\all_datasets\quebec_trees\2021_09_02_sbl_z1_rgb_cog\tiles'
      coco_path: '.\output\test\aggregator3\2021_09_02_sbl_z1_rgb_cog_coco_sf1p0_inferaggregator.json'
      output_folder: './output/test/segmenter1'
    model_type: 'vit_l'
    checkpoint_path: 'Data/models/sam/sam_vit_l_0b3195.pth'
    simplify_tolerance: 1.0
    padding_percentage: 2.0
    min_pixel_padding: 100