segmenter:
    io:
      coco_path: ''   # TODO TODO TODO
      tiles_path: ''   # TODO TODO TODO

      raster_path: 'Data/raw/quebec_trees_dataset_2021-09-02/2021-09-02/zone1/2021-09-02-sbl-z1-rgb-cog.tif'
      boxes_path: './output/test/aggregator1/aggregator_output_0p4_iou_0p7.geojson'
      output_folder: './output/test/segmenter1'
    raster_resolution:
      scale_factor: null
      ground_resolution: 0.05
    model_type: 'vit_l'
    checkpoint_path: 'Data/models/sam/sam_vit_l_0b3195.pth'
    simplify_tolerance: 1.0
    padding_percentage: 2.0
    min_pixel_padding: 100