io:
    raster_path: '/media/hugobaudchon/4 TB/SBL_test_run/20240429_sblgeneral_xprize100ha_m3m_rgb.tif'
    output_folder: './output/test/sbl_test_run'
    coco_n_workers: 5

detector_config:
    save_detector_intermediate_output: false

    tilerizer:
        tile_type: 'tile'
        tile_size: 1024
        tile_overlap: 0.5
        raster_resolution:
            scale_factor: null
            ground_resolution: 0.05
        ignore_black_white_alpha_tiles_threshold: 0.8
        area_of_interest: {
            aoi_config: 'generate',
            aoi_type: 'band',
            aois: {
              'infer': {
                'percentage': 1.0,
                'position': 1
              }
            }
        }

    detector:
        infer:
            io:
                checkpoint_state_dict_path: './output/detector_quebec/detector_checkpoint.pt'
            base_params:
                batch_size: 25
                box_predictions_per_image: 250
            architecture:
                architecture_name: 'basic'
                backbone_model_resnet_name: 'resnet50'

    aggregator:
        polygon_type: 'box'
        score_threshold: 0.4
        nms_threshold: 0.7
        nms_algorithm: 'iou'

segmenter_config:
    save_segmenter_intermediate_output: false

    tilerizer:
        tile_type: 'tile'
        tile_size: 1024
        tile_overlap: 0.5
        raster_resolution:
            scale_factor: null
            ground_resolution: 0.05
        ignore_black_white_alpha_tiles_threshold: 0.8
        area_of_interest: {
            aoi_config: 'generate',
            aoi_type: 'band',
            aois: {
              'infer': {
                'percentage': 1.0,
                'position': 1
              }
            }
        }

    segmenter:
        model_type: 'vit_l'
        checkpoint_path: 'Data/models/sam/sam_vit_l_0b3195.pth'
        simplify_tolerance: 1.0
        box_padding_percentage: 0.00


    aggregator:
        polygon_type: 'segmentation'
        score_threshold: 0.35
        nms_threshold: 0.5
        nms_algorithm: 'iou'

classifier_config:
    tilerizer:
        tile_type: 'polygon'
        tile_size: 1024
        tile_overlap: null
        raster_resolution:
            scale_factor: null
            ground_resolution: 0.05
        ignore_black_white_alpha_tiles_threshold: null
        area_of_interest: {
            aoi_config: 'generate',
            aoi_type: 'band',
            aois: {
              'infer': {
                'percentage': 1.0,
                'position': 1
              }
            }
        }

    embedder:
        infer:
            batch_size: 16
            siamese:
                checkpoint_path: 'models/siamese_classifier/checkpoint_0_20000.pth'
                architecture:
                    architecture_name: 'siamese'
                    backbone_model_resnet_name: 'resnet50'

    classifier:
        infer:
            scaler_checkpoint_path: 'models/siamese_classifier/scaler.joblib'
            classifier_checkpoint_path: 'models/siamese_classifier/svc.joblib'
            architecture:
                architecture_name: 'svm'
