raster_path: 'Data/raw/quebec_trees_dataset_2021-09-02/2021-09-02/zone1/2021-09-02-sbl-z1-rgb-cog.tif'
output_folder: 'Data/infer/scene_1'

tilerizer:
    tile_size: 1024
    tile_overlap: 0.5
    scale_factor: null
    ground_resolution: 0.05
    ignore_black_white_alpha_tiles_threshold: 0.8
    area_of_interest: {
        aoi_config: 'generate',
        aoi_type: 'band',
        aois: {
          'infer': {
            'percentage': 1.0,
            'position': 1
          }
        }
    }

detector:
    batch_size: 25
    box_predictions_per_image: 250
    checkpoint_state_dict_path: './output/detector_quebec/detector_checkpoint.pt'
    architecture:
        name: 'basic'
        rcnn_backbone_model_resnet_name: 'resnet50'

aggregator:
    score_threshold: 0.4
    nms_threshold: 0.7
    nms_algorithm: 'iou'